import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import register from "../extensions/brief.ts";

type Notice = { level: string; message: string };
type RunResult = {
  notices: Notice[];
  messages: string[];
  content: string | null;
  cache: string | null;
};

async function run(cwd: string, args: string): Promise<RunResult> {
  const notices: Notice[] = [];
  const messages: string[] = [];
  const ctx = {
    cwd,
    ui: { notify: (message: string, level: string) => notices.push({ level, message }) },
  };
  // Re-register each run so sendUserMessage captures into this run's array.
  let capturedHandler: ((args: string, ctx: unknown) => void | Promise<void>) | null = null;
  register({
    registerCommand: (name: string, def: { handler: (args: string, ctx: unknown) => void | Promise<void> }) => {
      assert.equal(name, "brief");
      capturedHandler = def.handler;
    },
    sendUserMessage: async (m: string) => {
      messages.push(m);
    },
  } as never);
  await capturedHandler!(args, ctx);

  const content = await readFile(path.join(cwd, "PROJECT_CONTEXT.md"), "utf8").catch(() => null);
  const cache = await readFile(path.join(cwd, ".pi", "brief.json"), "utf8").catch(() => null);
  return { notices, messages, content, cache };
}

async function tmp(): Promise<string> {
  return mkdtemp(path.join(tmpdir(), "brief-test-"));
}

async function appFixture(): Promise<string> {
  const dir = await tmp();
  for (const d of ["app", "components", "server", "lib", "prisma", ".github/workflows"]) {
    await mkdir(path.join(dir, d), { recursive: true });
  }
  await writeFile(
    path.join(dir, "package.json"),
    JSON.stringify({
      name: "fixture-app",
      scripts: { dev: "next dev", build: "next build", lint: "next lint", test: "vitest", typecheck: "tsc --noEmit", "db:migrate": "prisma migrate deploy" },
      dependencies: { next: "15.0.0", "@prisma/client": "5.0.0", "next-auth": "4.0.0", stripe: "14.0.0", zustand: "4.0.0", tailwindcss: "3.0.0" },
      devDependencies: { typescript: "5.0.0", vitest: "1.0.0", prisma: "5.0.0" },
    }),
    "utf8",
  );
  await writeFile(path.join(dir, "next.config.js"), "module.exports = {};\n", "utf8");
  await writeFile(path.join(dir, "tsconfig.json"), "{}\n", "utf8");
  await writeFile(path.join(dir, "Dockerfile"), "FROM node:20\n", "utf8");
  await writeFile(path.join(dir, "package-lock.json"), "{}\n", "utf8");
  await writeFile(path.join(dir, "README.md"), "# Fixture\n", "utf8");
  await writeFile(path.join(dir, ".env.example"), "DATABASE_URL=postgres://localhost/db\n", "utf8");
  for (let i = 0; i < 40; i += 1) {
    await writeFile(path.join(dir, "lib", `mod${i}.ts`), `export const x${i} = ${i};\n`, "utf8");
  }
  return dir;
}

test("compact default stays within line budget and avoids 'Not detected'", async () => {
  const dir = await appFixture();
  try {
    const r = await run(dir, "");
    assert.ok(r.content, "expected PROJECT_CONTEXT.md to be written");
    const lines = r.content!.split("\n").length;
    assert.ok(lines >= 45 && lines <= 80, `compact brief should be 45–80 lines, got ${lines}`);
    assert.doesNotMatch(r.content!, /Not detected/);
    assert.match(r.content!, /Generated by `brief-ctx` via `\/brief` \(compact\)\. Package version:/);
    assert.ok(r.cache, "expected .pi/brief.json cache to be written");
    assert.equal(r.notices.at(-1)?.level, "success");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("--full produces a broader brief than compact", async () => {
  const dir = await appFixture();
  try {
    const compact = (await run(dir, "")).content!.split("\n").length;
    const full = (await run(dir, "--full")).content!;
    assert.ok(full.split("\n").length >= compact, "full should be at least as long as compact");
    assert.match(full, /## Conventions/);
    assert.match(full, /## Top-Level Layout/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("--task appends a Task Lens without large expansion", async () => {
  const dir = await appFixture();
  try {
    const base = (await run(dir, "")).content!.split("\n").length;
    const r = await run(dir, '--task "add login page"');
    assert.match(r.content!, /## Task Lens/);
    assert.match(r.content!, /add login page/);
    assert.ok(r.content!.split("\n").length - base <= 12, "task mode should add only a small section");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("--dry-run writes nothing", async () => {
  const dir = await appFixture();
  try {
    const r = await run(dir, "--dry-run");
    assert.equal(r.content, null, "dry-run must not write PROJECT_CONTEXT.md");
    assert.equal(r.cache, null, "dry-run must not write the cache");
    assert.match(r.notices.at(-1)?.message ?? "", /Dry run/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("existing brief is updated idempotently by default", async () => {
  const dir = await appFixture();
  try {
    await writeFile(path.join(dir, "PROJECT_CONTEXT.md"), "# stale brief\n", "utf8");
    const r = await run(dir, "");
    const updated = await readFile(path.join(dir, "PROJECT_CONTEXT.md"), "utf8");
    assert.match(updated, /# Project Context/);
    assert.doesNotMatch(updated, /# stale brief/);
    assert.equal(r.notices.at(-1)?.level, "success");
    assert.match(r.notices.at(-1)?.message ?? "", /Updated PROJECT_CONTEXT\.md/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("never reads real .env files", async () => {
  const dir = await appFixture();
  const secret = "SUPER_SECRET_TOKEN_DO_NOT_LEAK_42";
  await writeFile(path.join(dir, ".env"), `API_KEY=${secret}\n`, "utf8");
  try {
    const r = await run(dir, "");
    assert.ok(r.content);
    assert.ok(!r.content!.includes(secret), "secret from .env must never appear in the brief");
    assert.ok(!(r.cache ?? "").includes(secret), "secret from .env must never appear in the cache");
    assert.ok(!r.content!.includes("`.env`"), ".env itself should not be listed as a key file");
    assert.match(r.content!, /\.env\.example/, ".env.example (safe) should still be referenced");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("--output rejects paths outside the project", async () => {
  const dir = await appFixture();
  const outside = path.join(path.dirname(dir), "escape.md");
  await rm(outside, { force: true });
  try {
    const r = await run(dir, "--output ../escape.md");
    assert.equal(r.notices.at(-1)?.level, "error");
    const leaked = await readFile(outside, "utf8").catch(() => null);
    assert.equal(leaked, null, "must not write outside the project directory");
  } finally {
    await rm(dir, { recursive: true, force: true });
    await rm(outside, { force: true });
  }
});

test("tiny project groups unknowns and omits 'Not detected'", async () => {
  const dir = await tmp();
  await writeFile(path.join(dir, "package.json"), JSON.stringify({ name: "tiny" }), "utf8");
  await writeFile(path.join(dir, "README.md"), "# tiny\n", "utf8");
  try {
    const r = await run(dir, "");
    assert.match(r.content!, /## Unknowns/);
    assert.doesNotMatch(r.content!, /Not detected/);
    assert.match(r.content!, /No test command detected\./);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("handles a missing package.json without throwing", async () => {
  const dir = await tmp();
  await writeFile(path.join(dir, "README.md"), "# no manifest\n", "utf8");
  try {
    const r = await run(dir, "");
    assert.ok(r.content, "should still generate a brief");
    assert.match(r.content!, /# Project Context/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("handles a malformed package.json without throwing", async () => {
  const dir = await tmp();
  await writeFile(path.join(dir, "package.json"), "{ this is not valid json", "utf8");
  await writeFile(path.join(dir, "README.md"), "# broken\n", "utf8");
  try {
    const r = await run(dir, "");
    assert.ok(r.content, "should still generate a brief despite bad JSON");
    assert.equal(r.notices.at(-1)?.level, "success");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("package/tool repos get useful project type, map, gallery, and switching context", async () => {
  const dir = await tmp();
  for (const d of ["src", "extensions", "prompts", "adapters/claude-code", "adapters/codex", "test", "types", ".github/workflows"]) {
    await mkdir(path.join(dir, d), { recursive: true });
  }
  await writeFile(
    path.join(dir, "package.json"),
    JSON.stringify({
      name: "brief-ctx",
      version: "1.1.0",
      author: "Someone With Auth In Field Name",
      bin: { "brief-ctx": "./src/cli.ts" },
      keywords: ["pi-package"],
      files: ["src", "extensions", "prompts", "preview.jpg"],
      scripts: { typecheck: "tsc -p tsconfig.json", test: "node --test" },
      pi: { extensions: ["./extensions"], prompts: ["./prompts"], image: "./preview.jpg" },
      devDependencies: { typescript: "latest" },
    }),
    "utf8",
  );
  await writeFile(path.join(dir, "README.md"), "# package\n", "utf8");
  await writeFile(path.join(dir, "CHANGELOG.md"), "# changes\n", "utf8");
  await writeFile(path.join(dir, "preview.jpg"), "fake", "utf8");
  await writeFile(path.join(dir, "pnpm-lock.yaml"), "lockfileVersion: '9'\n", "utf8");
  await writeFile(path.join(dir, "tsconfig.json"), "{}\n", "utf8");

  try {
    const r = await run(dir, "");
    assert.match(r.content!, /Project type: Pi package, CLI tool, multi-agent adapter package/);
    assert.match(r.content!, /Package: brief-ctx@1\.1\.0/);
    assert.match(r.content!, /Pi gallery: pi-package keyword, preview image configured/);
    assert.match(r.content!, /Package check: npm pack --dry-run/);
    assert.match(r.content!, /Pi extension: extensions\//);
    assert.match(r.content!, /Prompts: prompts\//);
    assert.match(r.content!, /Agent adapters: adapters\//);
    assert.match(r.content!, /Tests: test\//);
    assert.match(r.content!, /Types: types\//);
    assert.match(r.content!, /Package publishing:/);
    assert.match(r.content!, /## Agent Switching/);
    assert.match(r.content!, /Works in: Pi, CLI, Claude Code, Codex/);
    assert.doesNotMatch(r.content!, /Auth:/, "author field must not trigger auth risk");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("task lens routes package and scanner work to concrete files", async () => {
  const dir = await tmp();
  for (const d of ["src", "extensions", "test"]) await mkdir(path.join(dir, d), { recursive: true });
  await writeFile(
    path.join(dir, "package.json"),
    JSON.stringify({ name: "brief-ctx", bin: { "brief-ctx": "./src/cli.ts" }, scripts: { test: "node --test" }, devDependencies: { typescript: "latest" } }),
    "utf8",
  );
  await writeFile(path.join(dir, "README.md"), "# package\n", "utf8");
  try {
    const r = await run(dir, '--task "fix npm package gallery scanner risk map"');
    assert.match(r.content!, /## Task Lens/);
    assert.match(r.content!, /package\.json/);
    assert.match(r.content!, /README\.md/);
    assert.match(r.content!, /src\/core\.ts/);
    assert.match(r.content!, /test\/brief\.test\.ts/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("brief shows stale-context hints when cache signals change", async () => {
  const dir = await appFixture();
  try {
    await mkdir(path.join(dir, ".pi"), { recursive: true });
    await writeFile(
      path.join(dir, ".pi", "brief.json"),
      JSON.stringify({
        size: "tiny",
        stack: { projectType: "Node package", framework: null, packageManager: "yarn" },
        commands: { test: null, typecheck: null, lint: null },
        map: { entry: "old", core: null, adapters: null },
        risks: [],
        keyFiles: [{ file: "old.md", score: 1 }],
      }),
      "utf8",
    );
    const r = await run(dir, "");
    assert.match(r.content!, /## Changed Since Last Brief/);
    assert.match(r.content!, /Project size changed/);
    assert.match(r.content!, /Package manager changed/);
    assert.match(r.content!, /Risk areas changed/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("unknown flag is reported as an error", async () => {
  const dir = await appFixture();
  try {
    const r = await run(dir, "--nope");
    assert.equal(r.notices.at(-1)?.level, "error");
    assert.match(r.notices.at(-1)?.message ?? "", /Unknown argument/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});
