import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import register from "../extensions/brief.ts";

type Notice = { level: string; message: string };
type RunResult = {
  notices: Notice[];
  messages: string[];
  content: string | null;
  cache: string | null;
};

async function run(cwd: string, args: string): Promise<RunResult> {
  const notices: Notice[] = [];
  const messages: string[] = [];
  const ctx = {
    cwd,
    ui: { notify: (message: string, level: string) => notices.push({ level, message }) },
  };
  // Re-register each run so sendUserMessage captures into this run's array.
  let capturedHandler: ((args: string, ctx: unknown) => void | Promise<void>) | null = null;
  register({
    registerCommand: (_name: string, def: { handler: (args: string, ctx: unknown) => void | Promise<void> }) => {
      capturedHandler = def.handler;
    },
    sendUserMessage: async (m: string) => {
      messages.push(m);
    },
  } as never);
  await capturedHandler!(args, ctx);

  const content = await readFile(path.join(cwd, "PROJECT_CONTEXT.md"), "utf8").catch(() => null);
  const cache = await readFile(path.join(cwd, ".pi", "onboard.json"), "utf8").catch(() => null);
  return { notices, messages, content, cache };
}

async function tmp(): Promise<string> {
  return mkdtemp(path.join(tmpdir(), "onboard-test-"));
}

async function appFixture(): Promise<string> {
  const dir = await tmp();
  for (const d of ["app", "components", "server", "lib", "prisma", ".github/workflows"]) {
    await mkdir(path.join(dir, d), { recursive: true });
  }
  await writeFile(
    path.join(dir, "package.json"),
    JSON.stringify({
      name: "fixture-app",
      scripts: { dev: "next dev", build: "next build", lint: "next lint", test: "vitest", typecheck: "tsc --noEmit", "db:migrate": "prisma migrate deploy" },
      dependencies: { next: "15.0.0", "@prisma/client": "5.0.0", "next-auth": "4.0.0", stripe: "14.0.0", zustand: "4.0.0", tailwindcss: "3.0.0" },
      devDependencies: { typescript: "5.0.0", vitest: "1.0.0", prisma: "5.0.0" },
    }),
    "utf8",
  );
  await writeFile(path.join(dir, "next.config.js"), "module.exports = {};\n", "utf8");
  await writeFile(path.join(dir, "tsconfig.json"), "{}\n", "utf8");
  await writeFile(path.join(dir, "Dockerfile"), "FROM node:20\n", "utf8");
  await writeFile(path.join(dir, "package-lock.json"), "{}\n", "utf8");
  await writeFile(path.join(dir, "README.md"), "# Fixture\n", "utf8");
  await writeFile(path.join(dir, ".env.example"), "DATABASE_URL=postgres://localhost/db\n", "utf8");
  for (let i = 0; i < 40; i += 1) {
    await writeFile(path.join(dir, "lib", `mod${i}.ts`), `export const x${i} = ${i};\n`, "utf8");
  }
  return dir;
}

test("compact default stays within line budget and avoids 'Not detected'", async () => {
  const dir = await appFixture();
  try {
    const r = await run(dir, "");
    assert.ok(r.content, "expected PROJECT_CONTEXT.md to be written");
    const lines = r.content!.split("\n").length;
    assert.ok(lines >= 45 && lines <= 80, `compact brief should be 45–80 lines, got ${lines}`);
    assert.doesNotMatch(r.content!, /Not detected/);
    assert.match(r.content!, /Generated by `\/onboard` \(compact\)/);
    assert.ok(r.cache, "expected .pi/onboard.json cache to be written");
    assert.equal(r.notices.at(-1)?.level, "success");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("--full produces a broader brief than compact", async () => {
  const dir = await appFixture();
  try {
    const compact = (await run(dir, "")).content!.split("\n").length;
    const full = (await run(dir, "--refresh --full")).content!;
    assert.ok(full.split("\n").length >= compact, "full should be at least as long as compact");
    assert.match(full, /## Conventions/);
    assert.match(full, /## Top-Level Layout/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("--task appends a Task Lens without large expansion", async () => {
  const dir = await appFixture();
  try {
    const base = (await run(dir, "")).content!.split("\n").length;
    const r = await run(dir, '--refresh --task "add login page"');
    assert.match(r.content!, /## Task Lens/);
    assert.match(r.content!, /add login page/);
    assert.ok(r.content!.split("\n").length - base <= 12, "task mode should add only a small section");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("--dry-run writes nothing", async () => {
  const dir = await appFixture();
  try {
    const r = await run(dir, "--dry-run");
    assert.equal(r.content, null, "dry-run must not write PROJECT_CONTEXT.md");
    assert.equal(r.cache, null, "dry-run must not write the cache");
    assert.match(r.notices.at(-1)?.message ?? "", /Dry run/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("existing file is preserved without --refresh and the prompt says so", async () => {
  const dir = await appFixture();
  try {
    await run(dir, "");
    const first = await readFile(path.join(dir, "PROJECT_CONTEXT.md"), "utf8");
    const r = await run(dir, "");
    const second = await readFile(path.join(dir, "PROJECT_CONTEXT.md"), "utf8");
    assert.equal(first, second, "file should be untouched without --refresh");
    assert.equal(r.notices.at(-1)?.level, "warning");
    assert.match(r.messages[0] ?? "", /NOT overwritten/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("never reads real .env files", async () => {
  const dir = await appFixture();
  const secret = "SUPER_SECRET_TOKEN_DO_NOT_LEAK_42";
  await writeFile(path.join(dir, ".env"), `API_KEY=${secret}\n`, "utf8");
  try {
    const r = await run(dir, "--refresh");
    assert.ok(r.content);
    assert.ok(!r.content!.includes(secret), "secret from .env must never appear in the brief");
    assert.ok(!(r.cache ?? "").includes(secret), "secret from .env must never appear in the cache");
    assert.ok(!r.content!.includes("`.env`"), ".env itself should not be listed as a key file");
    assert.match(r.content!, /\.env\.example/, ".env.example (safe) should still be referenced");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("--output rejects paths outside the project", async () => {
  const dir = await appFixture();
  const outside = path.join(path.dirname(dir), "escape.md");
  await rm(outside, { force: true });
  try {
    const r = await run(dir, "--output ../escape.md");
    assert.equal(r.notices.at(-1)?.level, "error");
    const leaked = await readFile(outside, "utf8").catch(() => null);
    assert.equal(leaked, null, "must not write outside the project directory");
  } finally {
    await rm(dir, { recursive: true, force: true });
    await rm(outside, { force: true });
  }
});

test("tiny project groups unknowns and omits 'Not detected'", async () => {
  const dir = await tmp();
  await writeFile(path.join(dir, "package.json"), JSON.stringify({ name: "tiny" }), "utf8");
  await writeFile(path.join(dir, "README.md"), "# tiny\n", "utf8");
  try {
    const r = await run(dir, "");
    assert.match(r.content!, /## Unknowns/);
    assert.doesNotMatch(r.content!, /Not detected/);
    assert.match(r.content!, /No test command detected\./);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("handles a missing package.json without throwing", async () => {
  const dir = await tmp();
  await writeFile(path.join(dir, "README.md"), "# no manifest\n", "utf8");
  try {
    const r = await run(dir, "");
    assert.ok(r.content, "should still generate a brief");
    assert.match(r.content!, /# Project Context/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("handles a malformed package.json without throwing", async () => {
  const dir = await tmp();
  await writeFile(path.join(dir, "package.json"), "{ this is not valid json", "utf8");
  await writeFile(path.join(dir, "README.md"), "# broken\n", "utf8");
  try {
    const r = await run(dir, "");
    assert.ok(r.content, "should still generate a brief despite bad JSON");
    assert.equal(r.notices.at(-1)?.level, "success");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("unknown flag is reported as an error", async () => {
  const dir = await appFixture();
  try {
    const r = await run(dir, "--nope");
    assert.equal(r.notices.at(-1)?.level, "error");
    assert.match(r.notices.at(-1)?.message ?? "", /Unknown argument/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});
